# Subfamilias de cestas de mimbre ROCKING GIFTS (tema STYLE_NAME/SIZE_NAME/COLOR_NAME, BASKET).
# Los valores de modelo/tamaño/color de cada hijo están en spec.CHILDREN.

FAMILIES = {
    "paneras": {
        "parent_sku": "PARENT-PANERAS-MIMBRE-RG",
        "rep": "291147CLM",
        "children": ["2786199CLM", "291147CLM", "291148CLM", "291149CLM", "273526CLM", "273527DC"],
        "title": {
            "ES": "ROCKING GIFTS Panera de Mimbre - Cesta para Pan y Fruta Redonda, Ovalada o Rectangular, Decoración de Cocina",
            "DE": "ROCKING GIFTS Brotkorb aus Weide - Rund, Oval oder Rechteckig, Korb für Brot und Obst, Küchendeko",
            "FR": "ROCKING GIFTS Corbeille à Pain en Osier - Ronde, Ovale ou Rectangulaire, Panier à Pain et Fruits, Déco Cuisine",
            "IT": "ROCKING GIFTS Cestino per il Pane in Vimini - Rotondo, Ovale o Rettangolare, Cesto per Pane e Frutta, Decoro Cucina",
        },
        "bullets": {
            "ES": ["Paneras de mimbre trenzado en varios modelos (redonda, ovalada, rectangular, Sweet Home) y tamaños.",
                   "Ideales para servir pan, bollería o fruta en la mesa y para ordenar la cocina.",
                   "Fibra natural ligera y resistente con acabado artesanal y estilo rústico."],
            "DE": ["Geflochtene Brotkörbe aus Weide in mehreren Modellen (rund, oval, rechteckig, Sweet Home) und Größen.",
                   "Ideal zum Servieren von Brot, Gebäck oder Obst am Tisch und für Ordnung in der Küche.",
                   "Leichte, robuste Naturfaser mit handgemachtem Finish im Landhausstil."],
            "FR": ["Corbeilles à pain en osier tressé en plusieurs modèles (ronde, ovale, rectangulaire, Sweet Home) et tailles.",
                   "Idéales pour servir le pain, les viennoiseries ou les fruits et pour ranger la cuisine.",
                   "Fibre naturelle légère et résistante, finition artisanale de style champêtre."],
            "IT": ["Cestini per il pane in vimini intrecciato in vari modelli (rotondo, ovale, rettangolare, Sweet Home) e misure.",
                   "Ideali per servire pane, dolci o frutta a tavola e per mettere ordine in cucina.",
                   "Fibra naturale leggera e resistente con finitura artigianale in stile rustico."],
        },
        "desc": {
            "ES": "Paneras de mimbre ROCKING GIFTS para pan y fruta. Elige el modelo, el tamaño y el color para ver las medidas de cada panera.",
            "DE": "Brotkörbe aus Weide von ROCKING GIFTS für Brot und Obst. Wählen Sie Modell, Größe und Farbe, um die Maße jedes Korbes zu sehen.",
            "FR": "Corbeilles à pain en osier ROCKING GIFTS pour le pain et les fruits. Choisissez le modèle, la taille et la couleur pour voir les dimensions.",
            "IT": "Cestini per il pane in vimini ROCKING GIFTS per pane e frutta. Scegli modello, misura e colore per vedere le dimensioni di ogni cestino.",
        },
    },
    "forro": {
        "parent_sku": "PARENT-CESTAS-FORRO-MIMBRE-RG",
        "rep": "291157DCI",
        "children": ["291165DCI", "284539DCI", "291166DCI", "291158DCI", "291157DCI", "2873115DCI", "269482DCI", "2726439DCI", "2726440DCI", "312515DCI"],
        "title": {
            "ES": "ROCKING GIFTS Cestas de Mimbre Organizadoras - Con Forro de Tela, Ovaladas, Rectangulares o Redondas, Sets de Varios Tamaños",
            "DE": "ROCKING GIFTS Aufbewahrungskörbe aus Weide - Mit Stoffeinsatz, Oval, Rechteckig oder Rund, Sets in Mehreren Größen",
            "FR": "ROCKING GIFTS Paniers de Rangement en Osier - Avec Doublure en Tissu, Ovales, Rectangulaires ou Ronds, Sets de Plusieurs Tailles",
            "IT": "ROCKING GIFTS Cesti Organizer in Vimini - Con Fodera in Tessuto, Ovali, Rettangolari o Rotondi, Set di Più Misure",
        },
        "bullets": {
            "ES": ["Cestas pequeñas y medianas de mimbre, con o sin forro de tela, sueltas o en sets de 2 y 3 tamaños.",
                   "Perfectas para ordenar baño, armarios, estanterías, escritorio o la habitación infantil.",
                   "Mimbre trenzado natural o sintético, ligero y resistente, con acabado decorativo."],
            "DE": ["Kleine und mittlere Weidenkörbe, mit oder ohne Stoffeinsatz, einzeln oder als 2er- und 3er-Sets.",
                   "Perfekt für Ordnung in Bad, Schrank, Regal, Schreibtisch oder Kinderzimmer.",
                   "Natürliches oder synthetisches Weidengeflecht, leicht und robust, mit dekorativem Finish."],
            "FR": ["Petits et moyens paniers en osier, avec ou sans doublure en tissu, à l'unité ou en sets de 2 et 3 tailles.",
                   "Parfaits pour ranger la salle de bain, les placards, les étagères, le bureau ou la chambre d'enfant.",
                   "Osier tressé naturel ou synthétique, léger et résistant, finition décorative."],
            "IT": ["Cesti piccoli e medi in vimini, con o senza fodera in tessuto, singoli o in set da 2 e 3 misure.",
                   "Perfetti per ordinare bagno, armadi, scaffali, scrivania o cameretta.",
                   "Vimini intrecciato naturale o sintetico, leggero e resistente, con finitura decorativa."],
        },
        "desc": {
            "ES": "Cestas de mimbre organizadoras ROCKING GIFTS, con forro de tela o sin él. Elige el modelo, el tamaño y el color para ver las medidas de cada cesta o set.",
            "DE": "Aufbewahrungskörbe aus Weide von ROCKING GIFTS, mit oder ohne Stoffeinsatz. Wählen Sie Modell, Größe und Farbe, um die Maße jedes Korbes oder Sets zu sehen.",
            "FR": "Paniers de rangement en osier ROCKING GIFTS, avec ou sans doublure en tissu. Choisissez le modèle, la taille et la couleur pour voir les dimensions de chaque panier ou set.",
            "IT": "Cesti organizer in vimini ROCKING GIFTS, con o senza fodera in tessuto. Scegli modello, misura e colore per vedere le dimensioni di ogni cesto o set.",
        },
    },
    "boho": {
        "parent_sku": "PARENT-SETS-CESTAS-BOHO-RG",
        "rep": "284530CLM",
        "children": ["284530CLM", "291145CLM", "310103CLM", "284516CLM", "2873106CLM", "310104CLM", "287352CLM", "287363CLM", "287350CLM", "287353CLM", "269483CLM", "284515CLM", "310105CLM", "284556CLM"],
        "title": {
            "ES": "ROCKING GIFTS Set de Cestas de Mimbre Boho - Cestas con Tela, Asas o Tapa y Bandejas, Cajas de Almacenaje Multiusos",
            "DE": "ROCKING GIFTS Weidenkorb-Set Boho - Körbe mit Stoff, Griffen oder Deckel und Korbtabletts, Multifunktionale Aufbewahrung",
            "FR": "ROCKING GIFTS Set de Paniers en Osier Bohème - Paniers avec Tissu, Anses ou Couvercle et Plateaux, Boîtes de Rangement",
            "IT": "ROCKING GIFTS Set di Cesti in Vimini Boho - Cesti con Tessuto, Manici o Coperchio e Vassoi, Contenitori Multiuso",
        },
        "bullets": {
            "ES": ["Sets de 3 y 4 cestas de mimbre, alga o fibra de maíz en varios tamaños que encajan entre sí, con tela, asas o tapa.",
                   "Almacenaje multiusos para cocina, armario, baño o salón con un toque decorativo boho.",
                   "Incluye cestas bandeja y cestas trenzadas sueltas para completar la colección."],
            "DE": ["3er- und 4er-Sets aus Weide, Seegras oder Maisfaser in ineinander passenden Größen, mit Stoff, Griffen oder Deckel.",
                   "Vielseitige Aufbewahrung für Küche, Schrank, Bad oder Wohnzimmer mit dekorativem Boho-Touch.",
                   "Mit Tablettkörben und einzelnen geflochtenen Körben zur Ergänzung der Kollektion."],
            "FR": ["Sets de 3 et 4 paniers en osier, algue ou fibre de maïs de tailles emboîtables, avec tissu, anses ou couvercle.",
                   "Rangement polyvalent pour la cuisine, le placard, la salle de bain ou le salon, avec une touche bohème.",
                   "Comprend des paniers plateaux et des paniers tressés à l'unité pour compléter la collection."],
            "IT": ["Set da 3 e 4 cesti in vimini, alga o fibra di mais di misure impilabili, con tessuto, manici o coperchio.",
                   "Contenitori multiuso per cucina, armadio, bagno o soggiorno con un tocco decorativo boho.",
                   "Include cesti vassoio e cesti intrecciati singoli per completare la collezione."],
        },
        "desc": {
            "ES": "Sets de cestas de mimbre ROCKING GIFTS de estilo boho para almacenar y decorar. Elige el modelo, el tamaño y el color para ver las medidas y el número de cestas de cada set.",
            "DE": "Weidenkorb-Sets im Boho-Stil von ROCKING GIFTS zum Aufbewahren und Dekorieren. Wählen Sie Modell, Größe und Farbe, um Maße und Anzahl der Körbe jedes Sets zu sehen.",
            "FR": "Sets de paniers en osier ROCKING GIFTS de style bohème pour ranger et décorer. Choisissez le modèle, la taille et la couleur pour voir les dimensions et le nombre de paniers.",
            "IT": "Set di cesti in vimini ROCKING GIFTS in stile boho per riporre e decorare. Scegli modello, misura e colore per vedere dimensioni e numero di cesti di ogni set.",
        },
    },
    "artesanal": {
        "parent_sku": "PARENT-SETS-CESTAS-ARTESANAL-RG",
        "rep": "27324RGSG",
        "children": ["27324RGSG", "26744RGSG", "27654RGSG", "27649RGSG", "27164RGSG", "27168RGSG", "27325RGSG", "287362CLM", "22212967CLM"],
        "title": {
            "ES": "ROCKING GIFTS Set de Cestas Artesanales de Mimbre - Espadaña, Jacinto de Agua y Fibra Vegetal, Capazos con Asas en Varios Tamaños",
            "DE": "ROCKING GIFTS Set Handgemachter Körbe - Rohrkolben, Wasserhyazinthe und Pflanzenfaser, Körbe mit Griffen in Mehreren Größen",
            "FR": "ROCKING GIFTS Set de Paniers Artisanaux - Massette, Jacinthe d'Eau et Fibre Végétale, Paniers avec Anses en Plusieurs Tailles",
            "IT": "ROCKING GIFTS Set di Cesti Artigianali - Tifa, Giacinto d'Acqua e Fibra Vegetale, Cesti con Manici in Più Misure",
        },
        "bullets": {
            "ES": ["Sets de 2 y 3 cestas tejidas a mano en espadaña, jacinto de agua, fibra vegetal y cuerda.",
                   "Capazos con asas para guardar mantas, juguetes, revistas o plantas artificiales con estilo.",
                   "Cada pieza es artesanal, por lo que puede haber pequeñas diferencias de tono y trenzado."],
            "DE": ["2er- und 3er-Sets handgeflochtener Körbe aus Rohrkolben, Wasserhyazinthe, Pflanzenfaser und Kordel.",
                   "Körbe mit Griffen für Decken, Spielzeug, Zeitschriften oder Kunstpflanzen.",
                   "Jedes Stück ist handgemacht, daher sind kleine Unterschiede in Farbe und Geflecht möglich."],
            "FR": ["Sets de 2 et 3 paniers tressés à la main en massette, jacinthe d'eau, fibre végétale et corde.",
                   "Paniers avec anses pour ranger plaids, jouets, magazines ou plantes artificielles avec style.",
                   "Chaque pièce est artisanale : de légères différences de teinte et de tressage sont possibles."],
            "IT": ["Set da 2 e 3 cesti intrecciati a mano in tifa, giacinto d'acqua, fibra vegetale e corda.",
                   "Cesti con manici per coperte, giocattoli, riviste o piante artificiali.",
                   "Ogni pezzo è artigianale, quindi sono possibili piccole differenze di tono e intreccio."],
        },
        "desc": {
            "ES": "Sets de cestas artesanales ROCKING GIFTS tejidas a mano en fibras naturales. Elige el modelo, el tamaño y el color para ver las medidas de cada set.",
            "DE": "Sets handgemachter Körbe von ROCKING GIFTS aus Naturfasern. Wählen Sie Modell, Größe und Farbe, um die Maße jedes Sets zu sehen.",
            "FR": "Sets de paniers artisanaux ROCKING GIFTS tressés à la main en fibres naturelles. Choisissez le modèle, la taille et la couleur pour voir les dimensions.",
            "IT": "Set di cesti artigianali ROCKING GIFTS intrecciati a mano in fibre naturali. Scegli modello, misura e colore per vedere le dimensioni di ogni set.",
        },
    },
    "grandes": {
        "parent_sku": "PARENT-CESTOS-BAULES-MIMBRE-RG",
        "rep": "291144CLM",
        "children": ["312516DCI", "312523DCI", "291161DCI", "310102CLM", "291144CLM", "291143CLM"],
        "title": {
            "ES": "ROCKING GIFTS Cestos y Baúles de Mimbre Grandes - Con Tapa, para Ropa, Mantas y Juguetes, Sets de Almacenaje",
            "DE": "ROCKING GIFTS Große Weidenkörbe und Truhen - Mit Deckel, für Wäsche, Decken und Spielzeug, Aufbewahrungs-Sets",
            "FR": "ROCKING GIFTS Grands Paniers et Malles en Osier - Avec Couvercle, pour Linge, Plaids et Jouets, Sets de Rangement",
            "IT": "ROCKING GIFTS Grandi Ceste e Bauli in Vimini - Con Coperchio, per Biancheria, Coperte e Giocattoli, Set Contenitori",
        },
        "bullets": {
            "ES": ["Cestos altos, cestos de ropa y baúles de mimbre de gran capacidad, sueltos o en sets.",
                   "Para guardar ropa, mantas, toallas o juguetes en dormitorio, baño o salón.",
                   "Mimbre natural o sintético resistente; varios modelos con tapa y cestas interiores."],
            "DE": ["Hohe Körbe, Wäschekörbe und Truhen aus Weide mit großem Fassungsvermögen, einzeln oder als Set.",
                   "Zum Aufbewahren von Wäsche, Decken, Handtüchern oder Spielzeug in Schlafzimmer, Bad oder Wohnzimmer.",
                   "Robustes natürliches oder synthetisches Weidengeflecht; mehrere Modelle mit Deckel und Innenkörben."],
            "FR": ["Grands paniers, paniers à linge et malles en osier de grande capacité, à l'unité ou en sets.",
                   "Pour ranger linge, plaids, serviettes ou jouets dans la chambre, la salle de bain ou le salon.",
                   "Osier naturel ou synthétique résistant ; plusieurs modèles avec couvercle et paniers intérieurs."],
            "IT": ["Ceste alte, ceste portabiancheria e bauli in vimini di grande capacità, singoli o in set.",
                   "Per riporre biancheria, coperte, asciugamani o giocattoli in camera, bagno o soggiorno.",
                   "Vimini naturale o sintetico resistente; diversi modelli con coperchio e cesti interni."],
        },
        "desc": {
            "ES": "Cestos y baúles de mimbre ROCKING GIFTS de gran tamaño. Elige el modelo, el tamaño y el color para ver las medidas de cada cesto o set.",
            "DE": "Große Weidenkörbe und Truhen von ROCKING GIFTS. Wählen Sie Modell, Größe und Farbe, um die Maße jedes Korbes oder Sets zu sehen.",
            "FR": "Grands paniers et malles en osier ROCKING GIFTS. Choisissez le modèle, la taille et la couleur pour voir les dimensions de chaque panier ou set.",
            "IT": "Grandi ceste e bauli in vimini ROCKING GIFTS. Scegli modello, misura e colore per vedere le dimensioni di ogni cesta o set.",
        },
    },
    "revisteros": {
        "parent_sku": "PARENT-REVISTEROS-MIMBRE-RG",
        "rep": "269480CLM",
        "children": ["284524CLM", "269480CLM"],
        "title": {
            "ES": "ROCKING GIFTS Revistero de Mimbre con Asas - Alga o Fibra Natural, Cesta de Almacenaje para Salón y Sofá",
            "DE": "ROCKING GIFTS Zeitungskorb aus Weide mit Griffen - Seegras oder Naturfaser, Aufbewahrungskorb für Wohnzimmer",
            "FR": "ROCKING GIFTS Porte-Revues en Osier avec Anses - Algue ou Fibre Naturelle, Panier de Rangement pour Salon",
            "IT": "ROCKING GIFTS Portariviste in Vimini con Manici - Alga o Fibra Naturale, Cesto Contenitore per Soggiorno",
        },
        "bullets": {
            "ES": ["Revistero de mimbre con asas en alga o fibra natural, en dos tamaños.",
                   "Para revistas, periódicos, mantas o mandos junto al sofá.",
                   "Trenzado natural resistente con acabado decorativo."],
            "DE": ["Zeitungskorb aus Weide mit Griffen aus Seegras oder Naturfaser, in zwei Größen.",
                   "Für Zeitschriften, Zeitungen, Decken oder Fernbedienungen neben dem Sofa.",
                   "Robustes Naturgeflecht mit dekorativem Finish."],
            "FR": ["Porte-revues en osier avec anses en algue ou fibre naturelle, en deux tailles.",
                   "Pour magazines, journaux, plaids ou télécommandes à côté du canapé.",
                   "Tressage naturel résistant avec finition décorative."],
            "IT": ["Portariviste in vimini con manici in alga o fibra naturale, in due misure.",
                   "Per riviste, giornali, coperte o telecomandi accanto al divano.",
                   "Intreccio naturale resistente con finitura decorativa."],
        },
        "desc": {
            "ES": "Revisteros de mimbre ROCKING GIFTS con asas. Elige el modelo y el tamaño para ver las medidas.",
            "DE": "Zeitungskörbe aus Weide von ROCKING GIFTS mit Griffen. Wählen Sie Modell und Größe, um die Maße zu sehen.",
            "FR": "Porte-revues en osier ROCKING GIFTS avec anses. Choisissez le modèle et la taille pour voir les dimensions.",
            "IT": "Portariviste in vimini ROCKING GIFTS con manici. Scegli modello e misura per vedere le dimensioni.",
        },
    },
}
