# Familia "Cestas de mimbre ROCKING GIFTS" — tema STYLE_NAME/SIZE_NAME/COLOR_NAME, productType BASKET.
PARENT_SKU = "PARENT-CESTAS-MIMBRE-RG"
THEME = "STYLE_NAME/SIZE_NAME/COLOR_NAME"
MARKETS = {"ES": ("A1RKKUPIHCS9HS", "es_ES"), "DE": ("A1PA6795UKMFR9", "de_DE"), "FR": ("A13V1IB3VIYZZH", "fr_FR"), "IT": ("APJ6JRA9NG5V4", "it_IT")}

PARENT_TITLE = {
    "ES": "ROCKING GIFTS Cestas de Mimbre para Almacenaje y Decoración - Paneras, Sets de Cestas, Cestos y Baúles de Mimbre Natural",
    "DE": "ROCKING GIFTS Weidenkörbe zur Aufbewahrung und Dekoration - Brotkörbe, Korb-Sets, Wäschekörbe und Truhen aus Naturgeflecht",
    "FR": "ROCKING GIFTS Paniers en Osier pour Rangement et Décoration - Corbeilles à Pain, Sets de Paniers, Paniers à Linge et Malles en Osier",
    "IT": "ROCKING GIFTS Cesti in Vimini per Contenitori e Decorazione - Cestini per il Pane, Set di Cesti, Ceste Portabiancheria e Bauli in Vimini",
}

COLOR = {
    "Marrón": {"ES": "Marrón", "DE": "Braun", "FR": "Marron", "IT": "Marrone", "std": "Brown"},
    "Blanco": {"ES": "Blanco", "DE": "Weiß", "FR": "Blanc", "IT": "Bianco", "std": "White"},
    "Beige": {"ES": "Beige", "DE": "Beige", "FR": "Beige", "IT": "Beige", "std": "Beige"},
    "Verde": {"ES": "Verde", "DE": "Grün", "FR": "Vert", "IT": "Verde", "std": "Green"},
    "Gris": {"ES": "Gris", "DE": "Grau", "FR": "Gris", "IT": "Grigio", "std": "Grey"},
    "Natural": {"ES": "Natural", "DE": "Natur", "FR": "Naturel", "IT": "Naturale", "std": "Beige"},
    "Multicolor": {"ES": "Multicolor", "DE": "Mehrfarbig", "FR": "Multicolore", "IT": "Multicolore", "std": "Multicolor"},
}

STYLE = {
    "Baúl con tapa (set de 3)": {"DE": "Truhe mit Deckel (3er-Set)", "FR": "Malle avec couvercle (lot de 3)", "IT": "Baule con coperchio (set da 3)"},
    "Cesta rectangular bicolor": {"DE": "Rechteckiger Korb zweifarbig", "FR": "Panier rectangulaire bicolore", "IT": "Cesto rettangolare bicolore"},
    "Cesta ovalada con forro": {"DE": "Ovaler Korb mit Stoffeinsatz", "FR": "Panier ovale avec doublure", "IT": "Cesto ovale con fodera"},
    "Cesta rectangular con forro": {"DE": "Rechteckiger Korb mit Stoffeinsatz", "FR": "Panier rectangulaire avec doublure", "IT": "Cesto rettangolare con fodera"},
    "Cestas bicolor (set de 2)": {"DE": "Zweifarbige Körbe (2er-Set)", "FR": "Paniers bicolores (lot de 2)", "IT": "Cesti bicolore (set da 2)"},
    "Cestas redondas (set de 3)": {"DE": "Runde Körbe (3er-Set)", "FR": "Paniers ronds (lot de 3)", "IT": "Cesti rotondi (set da 3)"},
    "Cestas con forro": {"DE": "Körbe mit Stoffeinsatz", "FR": "Paniers avec doublure", "IT": "Cesti con fodera"},
    "Cestas tejido natural (set de 3)": {"DE": "Naturgeflochtene Körbe (3er-Set)", "FR": "Paniers tressage naturel (lot de 3)", "IT": "Cesti intreccio naturale (set da 3)"},
    "Cestas con forro (set de 3)": {"DE": "Körbe mit Stoffeinsatz (3er-Set)", "FR": "Paniers avec doublure (lot de 3)", "IT": "Cesti con fodera (set da 3)"},
    "Cesta bandeja": {"DE": "Tablettkorb", "FR": "Panier plateau", "IT": "Cesto vassoio"},
    "Panera (2 modelos)": {"DE": "Brotkorb (2 Modelle)", "FR": "Corbeille à pain (2 modèles)", "IT": "Cestino per il pane (2 modelli)"},
    "Panera redonda": {"DE": "Runder Brotkorb", "FR": "Corbeille à pain ronde", "IT": "Cestino per il pane rotondo"},
    "Panera ovalada": {"DE": "Ovaler Brotkorb", "FR": "Corbeille à pain ovale", "IT": "Cestino per il pane ovale"},
    "Panera rectangular": {"DE": "Rechteckiger Brotkorb", "FR": "Corbeille à pain rectangulaire", "IT": "Cestino per il pane rettangolare"},
    "Panera Sweet Home": {"DE": "Brotkorb Sweet Home", "FR": "Corbeille à pain Sweet Home", "IT": "Cestino per il pane Sweet Home"},
    "Cesta trenzada": {"DE": "Geflochtener Korb", "FR": "Panier tressé", "IT": "Cesto intrecciato"},
    "Cestas rectangulares (set de 3)": {"DE": "Rechteckige Körbe (3er-Set)", "FR": "Paniers rectangulaires (lot de 3)", "IT": "Cesti rettangolari (set da 3)"},
    "Cesto pongotodo (set de 2)": {"DE": "Allzweckkorb (2er-Set)", "FR": "Panier fourre-tout (lot de 2)", "IT": "Cesto portatutto (set da 2)"},
    "Cesto con tapa (2 modelos)": {"DE": "Korb mit Deckel (2 Modelle)", "FR": "Panier avec couvercle (2 modèles)", "IT": "Cesto con coperchio (2 modelli)"},
    "Cesto de ropa plegable": {"DE": "Faltbarer Wäschekorb", "FR": "Panier à linge pliable", "IT": "Cesta portabiancheria pieghevole"},
    "Baúles con 3 cestas (set de 2)": {"DE": "Truhen mit 3 Körben (2er-Set)", "FR": "Malles avec 3 paniers (lot de 2)", "IT": "Bauli con 3 cesti (set da 2)"},
    "Cestos altos (set de 2)": {"DE": "Hohe Körbe (2er-Set)", "FR": "Paniers hauts (lot de 2)", "IT": "Cesti alti (set da 2)"},
    "Cestas diseño flores (set de 3)": {"DE": "Körbe Blumendesign (3er-Set)", "FR": "Paniers motif fleurs (lot de 3)", "IT": "Cesti decoro fiori (set da 3)"},
    "Revistero de alga": {"DE": "Zeitungskorb aus Seegras", "FR": "Porte-revues en algue", "IT": "Portariviste in alga"},
    "Revistero de fibra natural": {"DE": "Zeitungskorb aus Naturfaser", "FR": "Porte-revues en fibre naturelle", "IT": "Portariviste in fibra naturale"},
    "Cajas cesta con tapa (set de 2)": {"DE": "Korbboxen mit Deckel (2er-Set)", "FR": "Boîtes panier avec couvercle (lot de 2)", "IT": "Scatole cesto con coperchio (set da 2)"},
    "Cubos cesta de jacinto (set de 2)": {"DE": "Wasserhyazinthen-Körbe (2er-Set)", "FR": "Paniers en jacinthe d'eau (lot de 2)", "IT": "Cesti in giacinto d'acqua (set da 2)"},
    "Cestas artesanales con cuerda (set de 3)": {"DE": "Handgemachte Körbe mit Kordel (3er-Set)", "FR": "Paniers artisanaux avec corde (lot de 3)", "IT": "Cesti artigianali con corda (set da 3)"},
    "Cestas planas con cuerda (set de 3)": {"DE": "Flache Körbe mit Kordel (3er-Set)", "FR": "Paniers plats avec corde (lot de 3)", "IT": "Cesti piatti con corda (set da 3)"},
    "Cestas pongotodo con asas (set de 3)": {"DE": "Allzweckkörbe mit Griffen (3er-Set)", "FR": "Paniers fourre-tout avec anses (lot de 3)", "IT": "Cesti portatutto con manici (set da 3)"},
    "Cestas con asas de espadaña (set de 3)": {"DE": "Rohrkolben-Körbe mit Griffen (3er-Set)", "FR": "Paniers en massette avec anses (lot de 3)", "IT": "Cesti in tifa con manici (set da 3)"},
    "Cestas ovales con asas (set de 3)": {"DE": "Ovale Körbe mit Griffen (3er-Set)", "FR": "Paniers ovales avec anses (lot de 3)", "IT": "Cesti ovali con manici (set da 3)"},
    "Cestas ovales con asas, fibra de maíz (set de 3)": {"DE": "Ovale Körbe mit Griffen, Maisfaser (3er-Set)", "FR": "Paniers ovales avec anses, fibre de maïs (lot de 3)", "IT": "Cesti ovali con manici, fibra di mais (set da 3)"},
    "Cestas ovales con tela (set de 3)": {"DE": "Ovale Körbe mit Stoff (3er-Set)", "FR": "Paniers ovales avec tissu (lot de 3)", "IT": "Cesti ovali con tessuto (set da 3)"},
    "Cestas rectangulares con tela (set de 3)": {"DE": "Rechteckige Körbe mit Stoff (3er-Set)", "FR": "Paniers rectangulaires avec tissu (lot de 3)", "IT": "Cesti rettangolari con tessuto (set da 3)"},
    "Cestas rectangulares de alga con tela (set de 3)": {"DE": "Rechteckige Seegraskörbe mit Stoff (3er-Set)", "FR": "Paniers rectangulaires en algue avec tissu (lot de 3)", "IT": "Cesti rettangolari in alga con tessuto (set da 3)"},
    "Cestas redondas con tapa (set de 3)": {"DE": "Runde Körbe mit Deckel (3er-Set)", "FR": "Paniers ronds avec couvercle (lot de 3)", "IT": "Cesti rotondi con coperchio (set da 3)"},
    "Cestas redondas con tela (set de 3)": {"DE": "Runde Körbe mit Stoff (3er-Set)", "FR": "Paniers ronds avec tissu (lot de 3)", "IT": "Cesti rotondi con tessuto (set da 3)"},
    "Cestas con asas (set de 3)": {"DE": "Körbe mit Griffen (3er-Set)", "FR": "Paniers avec anses (lot de 3)", "IT": "Cesti con manici (set da 3)"},
    "Bandejas cuadradas (set de 4)": {"DE": "Quadratische Korbtabletts (4er-Set)", "FR": "Plateaux carrés (lot de 4)", "IT": "Vassoi quadrati (set da 4)"},
    "Bandejas cuadradas de alga (set de 4)": {"DE": "Quadratische Seegras-Korbtabletts (4er-Set)", "FR": "Plateaux carrés en algue (lot de 4)", "IT": "Vassoi quadrati in alga (set da 4)"},
}

# sku: (modelo ES, tamaño, color)
CHILDREN = {
    "312516DCI": ("Baúl con tapa (set de 3)", "55 x 40 x 32 cm", "Verde"),
    "2873115DCI": ("Cesta rectangular bicolor", "21 x 16 x 10,5 cm", "Natural"),
    "291165DCI": ("Cesta ovalada con forro", "22 x 15 x 9 cm", "Beige"),
    "284539DCI": ("Cesta ovalada con forro", "23 x 20 x 8 cm", "Beige"),
    "291166DCI": ("Cesta rectangular con forro", "22 x 15 x 9 cm", "Marrón"),
    "312515DCI": ("Cestas bicolor (set de 2)", "30 x 30 x 25 cm", "Verde"),
    "2726439DCI": ("Cestas redondas (set de 3)", "15 x 15 x 18 cm", "Marrón"),
    "291158DCI": ("Cestas con forro", "23 x 17 x 10 cm", "Blanco"),
    "269482DCI": ("Cestas tejido natural (set de 3)", "16 x 16 x 14 cm", "Beige"),
    "291157DCI": ("Cestas con forro (set de 3)", "40 x 30 x 17 cm", "Blanco"),
    "310105CLM": ("Cesta bandeja", "27 x 18 x 7 cm", "Marrón"),
    "2786199CLM": ("Panera (2 modelos)", "18 x 18 x 14 cm", "Gris"),
    "291147CLM": ("Panera redonda", "18,5 x 18,5 x 9 cm", "Marrón"),
    "291148CLM": ("Panera ovalada", "22 x 15 x 9 cm", "Marrón"),
    "291149CLM": ("Panera rectangular", "22 x 15 x 9 cm", "Marrón"),
    "273526CLM": ("Panera Sweet Home", "20 x 9 cm", "Natural"),
    "273527DC": ("Panera Sweet Home", "26 cm", "Natural"),
    "284556CLM": ("Cesta trenzada", "17 x 17 x 7 cm", "Marrón"),
    "2726440DCI": ("Cestas rectangulares (set de 3)", "22 x 16 x 13 cm", "Marrón"),
    "312523DCI": ("Cesto con tapa (2 modelos)", "42 x 42 x 55 cm", "Verde"),
    "291161DCI": ("Cesto de ropa plegable", "37 x 22 x 55 cm", "Blanco"),
    "310102CLM": ("Baúles con 3 cestas (set de 2)", "56 x 48 x 42 cm", "Marrón"),
    "291144CLM": ("Baúles con 3 cestas (set de 2)", "60 x 40 x 40 cm", "Marrón"),
    "291143CLM": ("Cestos altos (set de 2)", "45 x 45 x 55 cm", "Marrón"),
    "22212967CLM": ("Cestas diseño flores (set de 3)", "3 tamaños", "Multicolor"),
    "284524CLM": ("Revistero de alga", "35 x 26 x 26 cm", "Marrón"),
    "269480CLM": ("Revistero de fibra natural", "40 x 28 x 26 cm", "Marrón"),
    "27325RGSG": ("Cajas cesta con tapa (set de 2)", "2 tamaños", "Marrón"),
    "27164RGSG": ("Cubos cesta de jacinto (set de 2)", "43 y 39 cm", "Marrón"),
    "27168RGSG": ("Cubos cesta de jacinto (set de 2)", "43 y 35 cm", "Marrón"),
    "27324RGSG": ("Cestas artesanales con cuerda (set de 3)", "3 tamaños", "Marrón"),
    "26744RGSG": ("Cestas planas con cuerda (set de 3)", "3 tamaños", "Blanco"),
    "287362CLM": ("Cestas pongotodo con asas (set de 3)", "42 x 42 x 48 cm", "Marrón"),
    "27654RGSG": ("Cestas con asas de espadaña (set de 3)", "29, 21 y 15 cm", "Beige"),
    "27649RGSG": ("Cestas con asas de espadaña (set de 3)", "36, 30 y 25 cm", "Beige"),
    "287352CLM": ("Cestas ovales con asas (set de 3)", "36 x 26 x 18 cm", "Blanco"),
    "287363CLM": ("Cestas ovales con asas (set de 3)", "36 x 26 x 18 cm", "Marrón"),
    "287350CLM": ("Cestas ovales con asas, fibra de maíz (set de 3)", "36 x 26 x 14 cm", "Marrón"),
    "284530CLM": ("Cestas ovales con tela (set de 3)", "31 x 31 x 16 cm", "Marrón"),
    "291145CLM": ("Cestas rectangulares con tela (set de 3)", "46 x 34 x 18 cm", "Marrón"),
    "310103CLM": ("Cestas rectangulares con tela (set de 3)", "41 x 31 x 16 cm", "Marrón"),
    "284516CLM": ("Cestas rectangulares de alga con tela (set de 3)", "31 x 31 x 16 cm", "Marrón"),
    "2873106CLM": ("Cestas redondas con tapa (set de 3)", "33 x 33 x 26 cm", "Marrón"),
    "310104CLM": ("Cestas redondas con tela (set de 3)", "30 x 30 x 20 cm", "Marrón"),
    "287353CLM": ("Cestas con asas (set de 3)", "33 x 33 x 23 cm", "Blanco"),
    "269483CLM": ("Bandejas cuadradas (set de 4)", "26 x 26 x 10 cm", "Marrón"),
    "284515CLM": ("Bandejas cuadradas de alga (set de 4)", "26 x 26 x 10 cm", "Marrón"),
}

EXCLUDED = {
    "310101CLM": "Amazon: sus datos no coinciden con el ASIN B0DLBSYFNC del catálogo (error 8541)",
    "273517CLM": "duplicado exacto de 310102CLM",
    "273519CLM": "duplicado de 310104CLM (mismo set y tamaño)",
    "269492CLM": "macetero", "269493CLM": "macetero", "22212917CLM": "macetero", "284554CLM": "macetero", "22212473CLM": "macetero",
    "306124CLM": "bote de cristal", "306125CLM": "bote de cristal", "306126CLM": "bote de cristal",
    "284540CLM": "marca Hogar Deco", "284540CLMFBA": "marca Hogar Deco (FBA)", "17022SG": "marca Vidal Regalos",
}

PARENT_CONTENT = {
    "ES": {
        "bullets": [
            "Colección de cestas de mimbre ROCKING GIFTS: paneras, cestas con forro de tela, sets de cestas, cestos de ropa, revisteros y baúles. Elige el modelo, el tamaño y el color que mejor encajen en tu casa.",
            "Fibras naturales trenzadas a mano (mimbre, alga, espadaña, jacinto de agua y fibra vegetal) con acabado resistente y duradero.",
            "Almacenaje práctico para cocina, baño, salón, dormitorio o habitación infantil: pan y fruta, juguetes, mantas, toallas, revistas o ropa.",
            "Decoración de estilo natural, boho y rústico que aporta calidez a cualquier estancia; muchos modelos vienen en sets de varios tamaños que encajan entre sí.",
            "Idea de regalo para inauguraciones, bodas o para quien quiere ordenar su casa con un toque decorativo.",
        ],
        "description": "Colección de cestas de mimbre ROCKING GIFTS para almacenar y decorar. Incluye paneras, cestas con forro de tela, sets de cestas de varios tamaños, cestos con tapa, cestos de ropa, revisteros y baúles, fabricados con fibras naturales trenzadas como mimbre, alga, espadaña y jacinto de agua. Selecciona el modelo, el tamaño y el color para ver las medidas y el contenido de cada variante.",
    },
    "DE": {
        "bullets": [
            "Weidenkorb-Kollektion von ROCKING GIFTS: Brotkörbe, Körbe mit Stoffeinsatz, Korb-Sets, Wäschekörbe, Zeitungskörbe und Truhen. Wählen Sie Modell, Größe und Farbe passend zu Ihrem Zuhause.",
            "Handgeflochtene Naturfasern (Weide, Seegras, Rohrkolben, Wasserhyazinthe und Pflanzenfaser) mit robuster, langlebiger Verarbeitung.",
            "Praktische Aufbewahrung für Küche, Bad, Wohnzimmer, Schlafzimmer oder Kinderzimmer: Brot und Obst, Spielzeug, Decken, Handtücher, Zeitschriften oder Wäsche.",
            "Natürliche Deko im Boho- und Landhausstil, die jedem Raum Wärme verleiht; viele Modelle als Sets in mehreren ineinander passenden Größen.",
            "Schöne Geschenkidee zum Einzug, zur Hochzeit oder für alle, die mit Stil Ordnung schaffen möchten.",
        ],
        "description": "Weidenkorb-Kollektion von ROCKING GIFTS zum Aufbewahren und Dekorieren. Mit Brotkörben, Körben mit Stoffeinsatz, Korb-Sets in mehreren Größen, Körben mit Deckel, Wäschekörben, Zeitungskörben und Truhen aus geflochtenen Naturfasern wie Weide, Seegras, Rohrkolben und Wasserhyazinthe. Wählen Sie Modell, Größe und Farbe, um Maße und Inhalt jeder Variante zu sehen.",
    },
    "FR": {
        "bullets": [
            "Collection de paniers en osier ROCKING GIFTS : corbeilles à pain, paniers avec doublure en tissu, sets de paniers, paniers à linge, porte-revues et malles. Choisissez le modèle, la taille et la couleur qui conviennent à votre intérieur.",
            "Fibres naturelles tressées à la main (osier, algue, massette, jacinthe d'eau et fibre végétale) avec une finition solide et durable.",
            "Rangement pratique pour la cuisine, la salle de bain, le salon, la chambre ou la chambre d'enfant : pain et fruits, jouets, plaids, serviettes, magazines ou linge.",
            "Décoration naturelle de style bohème et champêtre qui apporte de la chaleur à chaque pièce ; de nombreux modèles en sets de plusieurs tailles emboîtables.",
            "Idée cadeau pour une pendaison de crémaillère, un mariage ou pour ceux qui veulent ranger avec style.",
        ],
        "description": "Collection de paniers en osier ROCKING GIFTS pour ranger et décorer. Elle comprend des corbeilles à pain, des paniers avec doublure en tissu, des sets de paniers de plusieurs tailles, des paniers avec couvercle, des paniers à linge, des porte-revues et des malles en fibres naturelles tressées comme l'osier, l'algue, la massette et la jacinthe d'eau. Sélectionnez le modèle, la taille et la couleur pour voir les dimensions et le contenu de chaque variante.",
    },
    "IT": {
        "bullets": [
            "Collezione di cesti in vimini ROCKING GIFTS: cestini per il pane, cesti con fodera in tessuto, set di cesti, ceste portabiancheria, portariviste e bauli. Scegli il modello, la misura e il colore più adatti alla tua casa.",
            "Fibre naturali intrecciate a mano (vimini, alga, tifa, giacinto d'acqua e fibra vegetale) con finitura robusta e duratura.",
            "Contenitori pratici per cucina, bagno, soggiorno, camera da letto o cameretta: pane e frutta, giocattoli, coperte, asciugamani, riviste o biancheria.",
            "Decorazione naturale in stile boho e rustico che rende accogliente ogni ambiente; molti modelli in set di più misure impilabili.",
            "Idea regalo per una nuova casa, un matrimonio o per chi vuole fare ordine con stile.",
        ],
        "description": "Collezione di cesti in vimini ROCKING GIFTS per riporre e decorare. Comprende cestini per il pane, cesti con fodera in tessuto, set di cesti in più misure, cesti con coperchio, ceste portabiancheria, portariviste e bauli in fibre naturali intrecciate come vimini, alga, tifa e giacinto d'acqua. Seleziona modello, misura e colore per vedere dimensioni e contenuto di ogni variante.",
    },
}
