# Familia "Teteras de hierro colado ROCKING GIFTS" — tema SIZE_NAME/STYLE_NAME/COLOR_NAME (capacidad / diseño / color), TEAPOT.
# Reutiliza el SKU padre PARENT-TETERA-HIERRO (intento anterior, incompleto).
PRODUCT_TYPE = "TEAPOT"
THEME = "SIZE_NAME/STYLE_NAME/COLOR_NAME"
MARKETS = {"ES": ("A1RKKUPIHCS9HS", "es_ES"), "DE": ("A1PA6795UKMFR9", "de_DE"), "FR": ("A13V1IB3VIYZZH", "fr_FR"), "IT": ("APJ6JRA9NG5V4", "it_IT")}

COLOR = {
    "Amarillo": {"DE": "Gelb", "FR": "Jaune", "IT": "Giallo", "std": "Yellow"},
    "Azul": {"DE": "Blau", "FR": "Bleu", "IT": "Blu", "std": "Blue"},
    "Azul claro": {"DE": "Hellblau", "FR": "Bleu clair", "IT": "Azzurro", "std": "Blue"},
    "Azul gris": {"DE": "Graublau", "FR": "Bleu gris", "IT": "Blu grigio", "std": "Blue"},
    "Gris": {"DE": "Grau", "FR": "Gris", "IT": "Grigio", "std": "Grey"},
    "Marrón": {"DE": "Braun", "FR": "Marron", "IT": "Marrone", "std": "Brown"},
    "Morado": {"DE": "Lila", "FR": "Violet", "IT": "Viola", "std": "Purple"},
    "Mostaza": {"DE": "Senfgelb", "FR": "Moutarde", "IT": "Senape", "std": "Yellow"},
    "Naranja": {"DE": "Orange", "FR": "Orange", "IT": "Arancione", "std": "Orange"},
    "Negro": {"DE": "Schwarz", "FR": "Noir", "IT": "Nero", "std": "Black"},
    "Negro y dorado": {"DE": "Schwarz-Gold", "FR": "Noir et doré", "IT": "Nero e oro", "std": "Black"},
    "Rojo": {"DE": "Rot", "FR": "Rouge", "IT": "Rosso", "std": "Red"},
    "Turquesa": {"DE": "Türkis", "FR": "Turquoise", "IT": "Turchese", "std": "Turquoise"},
    "Verde": {"DE": "Grün", "FR": "Vert", "IT": "Verde", "std": "Green"},
}

STYLE = {
    "Clásica": {"DE": "Klassisch", "FR": "Classique", "IT": "Classica"},
    "Lisa": {"DE": "Glatt", "FR": "Lisse", "IT": "Liscia"},
    "Relieve": {"DE": "Relief", "FR": "Relief", "IT": "Rilievo"},
    "Relieve decorativo": {"DE": "Dekoratives Relief", "FR": "Relief décoratif", "IT": "Rilievo decorativo"},
    "Relieve cobrizo": {"DE": "Kupferfarbenes Relief", "FR": "Relief cuivré", "IT": "Rilievo ramato"},
    "Flores cobrizas": {"DE": "Kupferfarbene Blumen", "FR": "Fleurs cuivrées", "IT": "Fiori ramati"},
    "Relieve oriental": {"DE": "Orientalisches Relief", "FR": "Relief oriental", "IT": "Rilievo orientale"},
    "Olas": {"DE": "Wellen", "FR": "Vagues", "IT": "Onde"},
    "Detalles dorados": {"DE": "Goldene Details", "FR": "Détails dorés", "IT": "Dettagli dorati"},
    "Flores doradas": {"DE": "Goldene Blumen", "FR": "Fleurs dorées", "IT": "Fiori dorati"},
    "Estriada": {"DE": "Gerillt", "FR": "Striée", "IT": "Rigata"},
    "Estriada compacta": {"DE": "Gerillt kompakt", "FR": "Striée compacte", "IT": "Rigata compatta"},
    "Ramas": {"DE": "Zweige", "FR": "Branches", "IT": "Rami"},
    "Bambú": {"DE": "Bambus", "FR": "Bambou", "IT": "Bambù"},
    "Con embudo colador": {"DE": "Mit Siebeinsatz", "FR": "Avec entonnoir filtre", "IT": "Con imbuto filtro"},
    "Tapa decorada": {"DE": "Verzierter Deckel", "FR": "Couvercle décoré", "IT": "Coperchio decorato"},
    "Escamas": {"DE": "Schuppen", "FR": "Écailles", "IT": "Squame"},
    "Flores": {"DE": "Blumen", "FR": "Fleurs", "IT": "Fiori"},
    "Relieve floral clásico": {"DE": "Klassisches Blumenrelief", "FR": "Relief floral classique", "IT": "Rilievo floreale classico"},
    "Pétalos": {"DE": "Blütenblätter", "FR": "Pétales", "IT": "Petali"},
    "Texturizada": {"DE": "Strukturiert", "FR": "Texturée", "IT": "Testurizzata"},
    "Puntos": {"DE": "Punkte", "FR": "Points", "IT": "Puntini"},
    "Japonesa clásica": {"DE": "Klassisch japanisch", "FR": "Japonaise classique", "IT": "Giapponese classica"},
    "Círculos": {"DE": "Kreise", "FR": "Cercles", "IT": "Cerchi"},
    "Espiga": {"DE": "Ähre", "FR": "Épi", "IT": "Spiga"},
    "Crisantemo": {"DE": "Chrysantheme", "FR": "Chrysanthème", "IT": "Crisantemo"},
    "Girasol": {"DE": "Sonnenblume", "FR": "Tournesol", "IT": "Girasole"},
    "Con filtro infusor": {"DE": "Mit Teesieb", "FR": "Avec filtre infuseur", "IT": "Con filtro infusore"},
    "Set con 2 tazas y posavasos": {"DE": "Set mit 2 Tassen und Untersetzern", "FR": "Set avec 2 tasses et sous-verres", "IT": "Set con 2 tazze e sottobicchieri"},
    "Set con 2 tazas y platillos": {"DE": "Set mit 2 Tassen und Untertassen", "FR": "Set avec 2 tasses et soucoupes", "IT": "Set con 2 tazze e piattini"},
    "Set con 2 vasos y salvamanteles": {"DE": "Set mit 2 Bechern und Untersetzer", "FR": "Set avec 2 gobelets et dessous-de-plat", "IT": "Set con 2 bicchieri e sottopentola"},
}

# sku: (capacidad, diseño, color)
CHILDREN = {
    "29424SGI": ("0,3 L", "Clásica", "Amarillo"),
    "34185SGI": ("0,3 L", "Bambú", "Amarillo"),
    "39142SGI": ("0,3 L", "Lisa", "Amarillo"),
    "34181SGI": ("0,3 L", "Relieve", "Verde"),
    "34188SGI": ("0,3 L", "Relieve oriental", "Verde"),
    "39136SGI": ("0,3 L", "Bambú", "Verde"),
    "34182SGI": ("0,3 L", "Flores cobrizas", "Azul"),
    "34183SGI": ("0,3 L", "Relieve cobrizo", "Azul"),
    "34186SGI": ("0,3 L", "Relieve decorativo", "Azul"),
    "34190SGI": ("0,3 L", "Lisa", "Marrón"),
    "39135SGI": ("0,3 L", "Tapa decorada", "Naranja"),
    "39138SGI": ("0,3 L", "Bambú", "Rojo"),
    "39139SGI": ("0,3 L", "Escamas", "Rojo"),
    "39144SGI": ("0,3 L", "Clásica", "Rojo"),
    "39140SGI": ("0,3 L", "Olas", "Mostaza"),
    "39143SGI": ("0,3 L", "Clásica", "Negro"),
    "29433SGRG": ("0,35 L", "Con filtro infusor", "Azul claro"),
    "34180SGI": ("0,4 L", "Relieve", "Gris"),
    "34184SGI": ("0,4 L", "Olas", "Morado"),
    "34189SGI": ("0,4 L", "Detalles dorados", "Rojo"),
    "34549SGI": ("0,4 L", "Con embudo colador", "Naranja"),
    "34193SGI": ("0,6 L", "Estriada compacta", "Negro"),
    "39153SGI": ("0,6 L", "Estriada", "Negro"),
    "39154SGI": ("0,6 L", "Estriada", "Verde"),
    "39155SGI": ("0,6 L", "Estriada", "Rojo"),
    "39145SGI": ("0,6 L", "Flores", "Amarillo"),
    "39146SGI": ("0,6 L", "Flores", "Verde"),
    "39148SGI": ("0,6 L", "Flores", "Rojo"),
    "39152SGI": ("0,6 L", "Relieve floral clásico", "Rojo"),
    "39149SGI": ("0,6 L", "Bambú", "Amarillo"),
    "39150SGI": ("0,6 L", "Bambú", "Verde"),
    "39188SGI": ("0,6 L", "Set con 2 tazas y platillos", "Rojo"),
    "34194SGI": ("0,7 L", "Ramas", "Negro"),
    "34195SGI": ("0,7 L", "Flores doradas", "Rojo"),
    "39156SGI": ("0,7 L", "Estriada", "Negro"),
    "39158SGI": ("0,7 L", "Pétalos", "Verde"),
    "39159SGI": ("0,8 L", "Texturizada", "Negro"),
    "39160SGI": ("0,8 L", "Puntos", "Verde"),
    "39165SGI": ("0,8 L", "Puntos", "Turquesa"),
    "39166SGI": ("0,8 L", "Puntos", "Rojo"),
    "39168SGI": ("0,8 L", "Puntos", "Negro"),
    "39162SGI": ("0,8 L", "Japonesa clásica", "Rojo"),
    "39163SGI": ("0,8 L", "Flores", "Verde"),
    "39164SGI": ("0,8 L", "Flores", "Rojo"),
    "39185SGI": ("0,8 L", "Set con 2 tazas y posavasos", "Verde"),
    "39190SGI": ("0,8 L", "Set con 2 tazas y posavasos", "Morado"),
    "34202SGI": ("1 L", "Detalles dorados", "Turquesa"),
    "39169SGI": ("1 L", "Círculos", "Verde"),
    "39170SGI": ("1 L", "Flores", "Rojo"),
    "39172SGI": ("1 L", "Flores", "Amarillo"),
    "39173SGI": ("1 L", "Espiga", "Verde"),
    "39174SGI": ("1 L", "Espiga", "Rojo"),
    "39175SGI": ("1 L", "Texturizada", "Mostaza"),
    "39176SGI": ("1 L", "Texturizada", "Negro"),
    "34236SGI": ("1,1 L", "Bambú", "Verde"),
    "27750RGSG": ("1,1 L", "Con filtro infusor", "Negro"),
    "39178SGI": ("1,2 L", "Crisantemo", "Rojo"),
    "39179SGI": ("1,2 L", "Girasol", "Mostaza"),
    "39180SGI": ("1,2 L", "Puntos", "Negro"),
    "39182SGI": ("1,2 L", "Estriada", "Rojo"),
    "39183SGI": ("1,2 L", "Estriada", "Mostaza"),
    "39184SGI": ("1,2 L", "Estriada", "Negro"),
    "39189SGI": ("1,2 L", "Set con 2 vasos y salvamanteles", "Negro"),
    "27749RGSG": ("1,3 L", "Con filtro infusor", "Azul gris"),
    "22899RGSGFBA": ("1,8 L", "Con filtro infusor", "Negro y dorado"),
}

EXCLUDED = {
    "línea …SGRG/…RGSG archivada": "en la lista de borrado (sin ventas ni stock)",
    "…SG / …SGR Vidal Regalos": "otra marca",
    "salvamanteles, filtro de repuesto": "no son teteras",
}
