# Familia "Papel de regalo en rollo ROCKING GIFTS" — tema COLOR/SIZE (diseño / medida), GIFT_WRAP.
# Reutiliza el SKU padre "papelregalo" (ya existente en ES/DE/FR/IT con tema COLOR, que Amazon obliga a mantener;
# por eso el diseño va en `color`). Los hijos venían como GIFT_WRAP, FIGURINE, SCULPTURE y HOME: pasan todos a GIFT_WRAP.
PRODUCT_TYPE = "GIFT_WRAP"
THEME = "COLOR/SIZE"
MARKETS = {"ES": ("A1RKKUPIHCS9HS", "es_ES"), "DE": ("A1PA6795UKMFR9", "de_DE"), "FR": ("A13V1IB3VIYZZH", "fr_FR"), "IT": ("APJ6JRA9NG5V4", "it_IT")}

# pack: n = lote de n rollos; "mN" = "x N modelos" (el título no aclara si son N rollos); None = un rollo
PACK = {
    "ES": (lambda n: f"pack de {n}", lambda n: f"{n} modelos"),
    "DE": (lambda n: f"{n}er-Pack", lambda n: f"{n} Motive"),
    "FR": (lambda n: f"lot de {n}", lambda n: f"{n} modèles"),
    "IT": (lambda n: f"confezione da {n}", lambda n: f"{n} modelli"),
}

# diseño ES: (DE, FR, IT)
DESIGN = {
    "Animales y circo": ("Tiere und Zirkus", "Animaux et cirque", "Animali e circo"),
    "Balones azules y flores rosas": ("Blaue Bälle und rosa Blumen", "Ballons bleus et fleurs roses", "Palloni blu e fiori rosa"),
    "Basics": ("Basics", "Basics", "Basics"),
    "Bastones de caramelo y estrellas rojo y verde": ("Zuckerstangen und Sterne, rot und grün", "Sucres d'orge et étoiles rouge et vert", "Bastoncini di zucchero e stelle rosso e verde"),
    "Bolas de nieve, renos y árboles": ("Schneekugeln, Rentiere und Bäume", "Boules à neige, rennes et sapins", "Palle di neve, renne e alberi"),
    "Bolas navideñas y cuadro escocés": ("Weihnachtskugeln und Schottenkaro", "Boules de Noël et tartan", "Palline di Natale e tartan"),
    "Caballitos": ("Pferdchen", "Petits chevaux", "Cavallini"),
    "Caga Tió": ("Caga Tió", "Caga Tió", "Caga Tió"),
    "Caga Tió en catalán, verde": ("Caga Tió auf Katalanisch, grün", "Caga Tió en catalan, vert", "Caga Tió in catalano, verde"),
    "Casas y árboles verde y beige": ("Häuser und Bäume, grün und beige", "Maisons et sapins vert et beige", "Case e alberi verde e beige"),
    "Casitas de jengibre verde y rosa": ("Lebkuchenhäuschen, grün und rosa", "Maisons en pain d'épices vert et rose", "Casette di pan di zenzero verde e rosa"),
    "Casitas de jengibre y copos de nieve": ("Lebkuchenhäuschen und Schneeflocken", "Maisons en pain d'épices et flocons", "Casette di pan di zenzero e fiocchi di neve"),
    "Coches vintage": ("Vintage-Autos", "Voitures vintage", "Auto d'epoca"),
    "Confeti de colores": ("Buntes Konfetti", "Confettis colorés", "Coriandoli colorati"),
    "Coquette cerezas, fresas y flores": ("Coquette Kirschen, Erdbeeren und Blumen", "Coquette cerises, fraises et fleurs", "Coquette ciliegie, fragole e fiori"),
    "Corazones rojo y blanco, modelo I": ("Herzen rot und weiß, Modell I", "Cœurs rouge et blanc, modèle I", "Cuori rosso e bianco, modello I"),
    "Corazones rojo y blanco, modelo II": ("Herzen rot und weiß, Modell II", "Cœurs rouge et blanc, modèle II", "Cuori rosso e bianco, modello II"),
    "Corazones rojo y blanco, modelo III": ("Herzen rot und weiß, Modell III", "Cœurs rouge et blanc, modèle III", "Cuori rosso e bianco, modello III"),
    "Corazones rojo y dorado": ("Herzen rot und gold", "Cœurs rouge et doré", "Cuori rosso e oro"),
    "Corazones rojo y rosa": ("Herzen rot und rosa", "Cœurs rouge et rose", "Cuori rosso e rosa"),
    "Cuadros pastel": ("Karos in Pastell", "Carreaux pastel", "Quadretti pastello"),
    "Cuadros rojos navideños": ("Rote Weihnachtskaros", "Carreaux rouges de Noël", "Quadretti rossi natalizi"),
    "Cuadros vichy beige, rosa y turquesa": ("Vichy-Karo beige, rosa und türkis", "Vichy beige, rose et turquoise", "Quadretti vichy beige, rosa e turchese"),
    "Cumpleaños rosa, azul y blanco": ("Geburtstag rosa, blau und weiß", "Anniversaire rose, bleu et blanc", "Compleanno rosa, blu e bianco"),
    "Dinosaurios": ("Dinosaurier", "Dinosaures", "Dinosauri"),
    "Dinosaurios beige y azul": ("Dinosaurier beige und blau", "Dinosaures beige et bleu", "Dinosauri beige e blu"),
    "Elefantes y ratoncitos": ("Elefanten und Mäuschen", "Éléphants et souris", "Elefanti e topolini"),
    "Elfo": ("Elf", "Lutin", "Elfo"),
    "Elfos y rayas navideñas": ("Elfen und Weihnachtsstreifen", "Lutins et rayures de Noël", "Elfi e righe natalizie"),
    "Elfos, caramelos y estrellas": ("Elfen, Bonbons und Sterne", "Lutins, bonbons et étoiles", "Elfi, caramelle e stelle"),
    "Estrellas": ("Sterne", "Étoiles", "Stelle"),
    "Estrellas doradas burdeos y verde": ("Goldene Sterne, bordeaux und grün", "Étoiles dorées bordeaux et vert", "Stelle dorate bordeaux e verde"),
    "Estrellas doradas granate y verde": ("Goldene Sterne, weinrot und grün", "Étoiles dorées grenat et vert", "Stelle dorate granata e verde"),
    "Estrellas gris, rosa y azul": ("Sterne grau, rosa und blau", "Étoiles gris, rose et bleu", "Stelle grigio, rosa e blu"),
    "Estrellitas navideñas": ("Weihnachtssternchen", "Petites étoiles de Noël", "Stelline natalizie"),
    "Felicidades": ("Glückwünsche", "Félicitations", "Auguri"),
    "Flores amarillas y naranjas": ("Gelbe und orange Blumen", "Fleurs jaunes et orange", "Fiori gialli e arancioni"),
    "Flores amarillas, rojas y naranjas": ("Gelbe, rote und orange Blumen", "Fleurs jaunes, rouges et orange", "Fiori gialli, rossi e arancioni"),
    "Flores azul y blanco": ("Blumen blau und weiß", "Fleurs bleu et blanc", "Fiori blu e bianco"),
    "Flores azules, lunares verdes y flores rosas": ("Blaue Blumen, grüne Punkte und rosa Blumen", "Fleurs bleues, pois verts et fleurs roses", "Fiori blu, pois verdi e fiori rosa"),
    "Flores lila y blanco": ("Blumen lila und weiß", "Fleurs lilas et blanc", "Fiori lilla e bianco"),
    "Flores morado y rosa": ("Blumen lila und rosa", "Fleurs violet et rose", "Fiori viola e rosa"),
    "Flores morado y verde": ("Blumen lila und grün", "Fleurs violet et vert", "Fiori viola e verde"),
    "Flores morado, rosa y verde": ("Blumen lila, rosa und grün", "Fleurs violet, rose et vert", "Fiori viola, rosa e verde"),
    "Flores rosa y blanco": ("Blumen rosa und weiß", "Fleurs rose et blanc", "Fiori rosa e bianco"),
    "Flores rosa, azul y amarillo": ("Blumen rosa, blau und gelb", "Fleurs rose, bleu et jaune", "Fiori rosa, blu e giallo"),
    "Flores rosa, lila y amarillo": ("Blumen rosa, lila und gelb", "Fleurs rose, lilas et jaune", "Fiori rosa, lilla e giallo"),
    "Flores surtidas tonos suaves": ("Sortierte Blumen in sanften Tönen", "Fleurs assorties tons doux", "Fiori assortiti toni tenui"),
    "Flores tonos suaves": ("Blumen in sanften Tönen", "Fleurs tons doux", "Fiori toni tenui"),
    "Flores y cuadros lila y blanco": ("Blumen und Karos lila und weiß", "Fleurs et carreaux lilas et blanc", "Fiori e quadretti lilla e bianco"),
    "Flores y hojas tonos suaves": ("Blumen und Blätter in sanften Tönen", "Fleurs et feuilles tons doux", "Fiori e foglie toni tenui"),
    "Flores y puntos verde, rosa y azul": ("Blumen und Punkte grün, rosa und blau", "Fleurs et pois vert, rose et bleu", "Fiori e pois verde, rosa e blu"),
    "Floral rosa, amarillo y blanco": ("Blumenmuster rosa, gelb und weiß", "Floral rose, jaune et blanc", "Floreale rosa, giallo e bianco"),
    "Galletas de Navidad": ("Weihnachtsplätzchen", "Biscuits de Noël", "Biscotti di Natale"),
    "Gorros de Papá Noel y caramelos": ("Weihnachtsmützen und Bonbons", "Bonnets de Père Noël et bonbons", "Cappelli di Babbo Natale e caramelle"),
    "Gorros de Papá Noel, caramelos y campanas": ("Weihnachtsmützen, Bonbons und Glocken", "Bonnets de Père Noël, bonbons et cloches", "Cappelli di Babbo Natale, caramelle e campane"),
    "Gorros de Papá Noel, caramelos y galletas": ("Weihnachtsmützen, Bonbons und Plätzchen", "Bonnets de Père Noël, bonbons et biscuits", "Cappelli di Babbo Natale, caramelle e biscotti"),
    "Kraft Panot de Barcelona marrón y gris": ("Kraft Panot de Barcelona, braun und grau", "Kraft Panot de Barcelone marron et gris", "Kraft Panot di Barcellona marrone e grigio"),
    "Kraft Papá Noel y muñecos de nieve": ("Kraft Weihnachtsmann und Schneemänner", "Kraft Père Noël et bonshommes de neige", "Kraft Babbo Natale e pupazzi di neve"),
    "Kraft casas y copos de nieve": ("Kraft Häuser und Schneeflocken", "Kraft maisons et flocons", "Kraft case e fiocchi di neve"),
    "Kraft corazones San Valentín": ("Kraft Valentinsherzen", "Kraft cœurs Saint-Valentin", "Kraft cuori San Valentino"),
    "Kraft cumpleaños beige y negro": ("Kraft Geburtstag beige und schwarz", "Kraft anniversaire beige et noir", "Kraft compleanno beige e nero"),
    "Kraft cumpleaños con globos": ("Kraft Geburtstag mit Luftballons", "Kraft anniversaire avec ballons", "Kraft compleanno con palloncini"),
    "Kraft felicidades, rayas y topos": ("Kraft Glückwünsche, Streifen und Punkte", "Kraft félicitations, rayures et pois", "Kraft auguri, righe e pois"),
    "Kraft gorros de Papá Noel y muñecos de nieve": ("Kraft Weihnachtsmützen und Schneemänner", "Kraft bonnets de Père Noël et bonshommes de neige", "Kraft cappelli di Babbo Natale e pupazzi di neve"),
    "Kraft lunares, estrellas y manchas": ("Kraft Punkte, Sterne und Flecken", "Kraft pois, étoiles et taches", "Kraft pois, stelle e macchie"),
    "Kraft renos y árboles": ("Kraft Rentiere und Bäume", "Kraft rennes et sapins", "Kraft renne e alberi"),
    "Kraft renos, árboles y bolas": ("Kraft Rentiere, Bäume und Kugeln", "Kraft rennes, sapins et boules", "Kraft renne, alberi e palline"),
    "Lápices y colegio": ("Bleistifte und Schule", "Crayons et école", "Matite e scuola"),
    "Letras": ("Buchstaben", "Lettres", "Lettere"),
    "Lisos lila, turquesa y rosa": ("Uni lila, türkis und rosa", "Unis lilas, turquoise et rose", "Tinta unita lilla, turchese e rosa"),
    "Lunares, corazones y rayas": ("Punkte, Herzen und Streifen", "Pois, cœurs et rayures", "Pois, cuori e righe"),
    "Mariposas azul y lila": ("Schmetterlinge blau und lila", "Papillons bleu et lilas", "Farfalle blu e lilla"),
    "Mariposas azul y rosa": ("Schmetterlinge blau und rosa", "Papillons bleu et rose", "Farfalle blu e rosa"),
    "Mariposas de colores": ("Bunte Schmetterlinge", "Papillons colorés", "Farfalle colorate"),
    "Mascotas": ("Haustiere", "Animaux de compagnie", "Animali domestici"),
    "Metalizado rojo, dorado y plateado": ("Metallic rot, gold und silber", "Métallisé rouge, doré et argenté", "Metallizzato rosso, oro e argento"),
    "Minimalista rosa y verde pálido": ("Minimalistisch rosa und blassgrün", "Minimaliste rose et vert pâle", "Minimalista rosa e verde pallido"),
    "Navidad": ("Weihnachten", "Noël", "Natale"),
    "Navidad I": ("Weihnachten I", "Noël I", "Natale I"),
    "Navidad II": ("Weihnachten II", "Noël II", "Natale II"),
    "Navidad III": ("Weihnachten III", "Noël III", "Natale III"),
    "Navidad en colores pastel": ("Weihnachten in Pastellfarben", "Noël couleurs pastel", "Natale in colori pastello"),
    "Navidad rojo y verde": ("Weihnachten rot und grün", "Noël rouge et vert", "Natale rosso e verde"),
    "Nubes": ("Wolken", "Nuages", "Nuvole"),
    "Olentzero": ("Olentzero", "Olentzero", "Olentzero"),
    "Oro": ("Gold", "Or", "Oro"),
    "Osos y corazones granate": ("Bären und Herzen, weinrot", "Ours et cœurs grenat", "Orsetti e cuori granata"),
    "Ositos": ("Teddybären", "Oursons", "Orsetti"),
    "Ovejitas y nubes": ("Schäfchen und Wolken", "Moutons et nuages", "Pecorelle e nuvole"),
    "Panot de Barcelona gris": ("Panot de Barcelona, grau", "Panot de Barcelone gris", "Panot di Barcellona grigio"),
    "Papá Noel": ("Weihnachtsmann", "Père Noël", "Babbo Natale"),
    "Papá Noel, regalos y estrellas": ("Weihnachtsmann, Geschenke und Sterne", "Père Noël, cadeaux et étoiles", "Babbo Natale, regali e stelle"),
    "Papá Noel, renos y galletas de jengibre": ("Weihnachtsmann, Rentiere und Lebkuchen", "Père Noël, rennes et pains d'épices", "Babbo Natale, renne e omini di pan di zenzero"),
    "Pasteles y velas": ("Torten und Kerzen", "Gâteaux et bougies", "Torte e candeline"),
    "Perros y gatos": ("Hunde und Katzen", "Chiens et chats", "Cani e gatti"),
    "Rayas bicolor": ("Zweifarbige Streifen", "Rayures bicolores", "Righe bicolore"),
    "Rayas y Papá Noel con renos": ("Streifen und Weihnachtsmann mit Rentieren", "Rayures et Père Noël avec rennes", "Righe e Babbo Natale con renne"),
    "Rayas y lunares blanco y negro": ("Streifen und Punkte schwarz-weiß", "Rayures et pois noir et blanc", "Righe e pois bianco e nero"),
    "Reyes Magos": ("Heilige Drei Könige", "Rois mages", "Re Magi"),
    "Reyes Magos con camellos": ("Heilige Drei Könige mit Kamelen", "Rois mages avec chameaux", "Re Magi con cammelli"),
    "Reyes Magos con camellos y palmeras": ("Heilige Drei Könige mit Kamelen und Palmen", "Rois mages avec chameaux et palmiers", "Re Magi con cammelli e palme"),
    "Reyes Magos infantil": ("Heilige Drei Könige für Kinder", "Rois mages pour enfants", "Re Magi per bambini"),
    "Reyes Magos Melchor, Gaspar y Baltasar": ("Heilige Drei Könige Melchior, Kaspar und Balthasar", "Rois mages Melchior, Gaspard et Balthazar", "Re Magi Melchiorre, Gaspare e Baldassarre"),
    "Rosas": ("Rosen", "Roses", "Rose"),
    "Soldados": ("Soldaten", "Soldats", "Soldatini"),
    "Sweet Christmas": ("Sweet Christmas", "Sweet Christmas", "Sweet Christmas"),
    "Topos dorados rosa y blanco": ("Goldene Punkte, rosa und weiß", "Pois dorés rose et blanc", "Pois dorati rosa e bianco"),
    "Unicornios": ("Einhörner", "Licornes", "Unicorni"),
}

S2, S3, S5 = "200x70 cm", "300x100 cm", "500x70 cm"
# sku: (medida, pack, diseño ES)
CHILDREN = {
    # 200x70 cm
    "304103CLM": (S2, 2, "Topos dorados rosa y blanco"),
    "304105CLM": (S2, 3, "Estrellitas navideñas"),
    "304106CLM": (S2, 2, "Corazones rojo y blanco, modelo I"),
    "3041285CLM": (S2, 2, "Corazones rojo y blanco, modelo II"),
    "3041286CLM": (S2, 2, "Corazones rojo y blanco, modelo III"),
    "3041284CLM": (S2, 2, "Corazones rojo y dorado"),
    "304109CLM": (S2, 2, "Navidad en colores pastel"),
    "3041101CLM": (S2, "m2", "Soldados"),
    "3041104CLM": (S2, 3, "Minimalista rosa y verde pálido"),
    "3041106CLM": (S2, 2, "Felicidades"),
    "304110CLM": (S2, "m2", "Caga Tió"),
    "304111CLM": (S2, "m2", "Estrellas"),
    "3041142CLM": (S2, 2, "Dinosaurios"),
    "3041143CLM": (S2, 2, "Unicornios"),
    "3041144CLM": (S2, 2, "Letras"),
    "3041145CLM": (S2, 2, "Kraft corazones San Valentín"),
    "304114CLM": (S2, 3, "Kraft cumpleaños beige y negro"),
    "304115CLM": (S2, None, "Panot de Barcelona gris"),
    "3041201CLM": (S2, None, "Kraft Panot de Barcelona marrón y gris"),
    "3041178CLM": (S2, 2, "Balones azules y flores rosas"),
    "304118CLM": (S2, "m3", "Oro"),
    "3041200CLM": (S2, 3, "Floral rosa, amarillo y blanco"),
    "3041202CLM": (S2, 2, "Coches vintage"),
    "3041203CLM": (S2, 3, "Lisos lila, turquesa y rosa"),
    "304123CLM": (S2, "m2", "Nubes"),
    "3041258CLM": (S2, "m3", "Basics"),
    "3041260CLM": (S2, "m3", "Mascotas"),
    "304128CLM": (S2, 3, "Cuadros pastel"),
    "3041291CLM": (S2, 3, "Flores azul y blanco"),
    "3041292CLM": (S2, 3, "Flores rosa y blanco"),
    "3041293CLM": (S2, 3, "Flores lila y blanco"),
    "3041298CLM": (S2, 2, "Flores y cuadros lila y blanco"),
    "3041299CLM": (S2, 2, "Mariposas de colores"),
    "304129CLM": (S2, 2, "Confeti de colores"),
    "3041300CLM": (S2, None, "Rosas"),
    "3041301CLM": (S2, 2, "Lápices y colegio"),
    "3041302CLM": (S2, 2, "Ositos"),
    "3041303CLM": (S2, 2, "Caballitos"),
    "3041304CLM": (S2, 2, "Dinosaurios beige y azul"),
    "3041305CLM": (S2, 2, "Elefantes y ratoncitos"),
    "3041314CLM": (S2, None, "Reyes Magos infantil"),
    "304178CLM": (S2, "m2", "Reyes Magos"),
    "3041322CLM": (S2, "m2", "Navidad I"),
    "3041356CLM": (S2, "m2", "Navidad II"),
    "3041359CLM": (S2, "m2", "Navidad III"),
    "3041365CLM": (S2, "m3", "Navidad"),
    "3041330CLM": (S2, "m2", "Elfo"),
    "3041338CLM": (S2, "m2", "Olentzero"),
    "304155CLM": (S2, 2, "Galletas de Navidad"),
    "304165CLM": (S2, 3, "Cuadros rojos navideños"),
    "3041346DCI": (S2, 2, "Kraft Papá Noel y muñecos de nieve"),
    "3041349DCI": (S2, 2, "Kraft casas y copos de nieve"),
    "3041362DCI": (S2, 2, "Estrellas doradas granate y verde"),
    "3041398DCI": (S2, 2, "Perros y gatos"),
    "3041400DCI": (S2, 3, "Flores azules, lunares verdes y flores rosas"),
    "3041402DCI": (S2, 3, "Rayas y lunares blanco y negro"),
    "3041404DCI": (S2, 2, "Flores amarillas, rojas y naranjas"),
    "3041406DCI": (S2, 2, "Flores morado, rosa y verde"),
    "3041408DCI": (S2, 3, "Kraft cumpleaños con globos"),
    "3041410DCI": (S2, 3, "Lunares, corazones y rayas"),
    "3041412DCI": (S2, 2, "Pasteles y velas"),
    "3041418DCI": (S2, 3, "Metalizado rojo, dorado y plateado"),
    "3041430DCI": (S2, 2, "Corazones rojo y rosa"),
    "3041435DCI": (S2, 3, "Flores surtidas tonos suaves"),
    "3041450DCI": (S2, 3, "Flores rosa, azul y amarillo"),
    "3041495DCI": (S2, 3, "Flores y hojas tonos suaves"),
    "3041446DCI": (S2, 3, "Rayas bicolor"),
    "3041448DCI": (S2, 2, "Mariposas azul y lila"),
    "3041452DCI": (S2, 3, "Kraft lunares, estrellas y manchas"),
    "3041455DCI": (S2, 3, "Coquette cerezas, fresas y flores"),
    "3041457DCI": (S2, 3, "Animales y circo"),
    "3041459DCI": (S2, 3, "Ovejitas y nubes"),
    "3041467DCI": (S2, None, "Reyes Magos con camellos y palmeras"),
    "3041469DCI": (S2, 3, "Reyes Magos Melchor, Gaspar y Baltasar"),
    "3041477DCI": (S2, 3, "Papá Noel"),
    "3041483DCI": (S2, 3, "Elfos, caramelos y estrellas"),
    "3041488DCI": (S2, 3, "Papá Noel, regalos y estrellas"),
    "3041492DCI": (S2, 2, "Bolas de nieve, renos y árboles"),
    "3041496DCI": (S2, 2, "Casitas de jengibre verde y rosa"),
    "3041498DCI": (S2, 2, "Bastones de caramelo y estrellas rojo y verde"),
    "3041500DCI": (S2, 2, "Gorros de Papá Noel y caramelos"),
    "3041502DCI": (S2, 2, "Bolas navideñas y cuadro escocés"),
    "3041504DCI": (S2, 2, "Kraft renos y árboles"),
    # 300x100 cm
    "3041368DCI": (S3, 2, "Reyes Magos con camellos"),
    "3041369DCI": (S3, 2, "Rayas y Papá Noel con renos"),
    "3041370DCI": (S3, 2, "Elfos y rayas navideñas"),
    "3041371CLM": (S3, "m2", "Olentzero"),
    "3041373DCI": (S3, 2, "Kraft gorros de Papá Noel y muñecos de nieve"),
    "3041374DCI": (S3, 2, "Kraft casas y copos de nieve"),
    "3041375CLM": (S3, "m2", "Navidad I"),
    "3041376CLM": (S3, "m2", "Navidad II"),
    "3041377DCI": (S3, 2, "Estrellas doradas burdeos y verde"),
    "3041378CLM": (S3, "m3", "Navidad"),
    "3041379CLM": (S3, None, "Reyes Magos"),
    "3041380CLM": (S3, "m2", "Soldados"),
    "3041381DCI": (S3, 3, "Papá Noel, renos y galletas de jengibre"),
    "3041382CLM": (S3, "m2", "Estrellas"),
    "3041383CLM": (S3, "m2", "Oro"),
    "3041384CLM": (S3, "m2", "Sweet Christmas"),
    "3041385CLM": (S3, None, "Caga Tió"),
    "3041401DCI": (S3, 3, "Flores y puntos verde, rosa y azul"),
    "3041403DCI": (S3, 3, "Rayas y lunares blanco y negro"),
    "3041405DCI": (S3, 2, "Flores amarillas y naranjas"),
    "3041407DCI": (S3, 2, "Flores morado y rosa"),
    "3041409DCI": (S3, 3, "Kraft cumpleaños con globos"),
    "3041411DCI": (S3, 3, "Lunares, corazones y rayas"),
    "3041413DCI": (S3, 2, "Pasteles y velas"),
    "3041419DCI": (S3, 3, "Metalizado rojo, dorado y plateado"),
    "3041431DCI": (S3, 2, "Corazones rojo y rosa"),
    "3041433DCI": (S3, 2, "Osos y corazones granate"),
    "3041436DCI": (S3, 3, "Flores tonos suaves"),
    "3041445DCI": (S3, 3, "Flores morado y verde"),
    "3041451DCI": (S3, 3, "Flores rosa, lila y amarillo"),
    "3041447DCI": (S3, 3, "Rayas bicolor"),
    "3041449DCI": (S3, 2, "Mariposas azul y rosa"),
    "3041453DCI": (S3, 3, "Kraft lunares, estrellas y manchas"),
    "3041458DCI": (S3, 3, "Animales y circo"),
    "3041460DCI": (S3, 3, "Ovejitas y nubes"),
    "3041468DCI": (S3, None, "Reyes Magos con camellos y palmeras"),
    "3041470DCI": (S3, 3, "Reyes Magos Melchor, Gaspar y Baltasar"),
    "3041478DCI": (S3, 3, "Papá Noel"),
    "3041484DCI": (S3, 3, "Elfos, caramelos y estrellas"),
    "3041489DCI": (S3, 3, "Papá Noel, regalos y estrellas"),
    "3041493DCI": (S3, 2, "Navidad rojo y verde"),
    "3041497DCI": (S3, 2, "Casitas de jengibre y copos de nieve"),
    "3041499DCI": (S3, 2, "Bastones de caramelo y estrellas rojo y verde"),
    "3041501DCI": (S3, 2, "Gorros de Papá Noel, caramelos y campanas"),
    "3041503DCI": (S3, 2, "Bolas navideñas y cuadro escocés"),
    "3041505DCI": (S3, 2, "Kraft renos, árboles y bolas"),
    # 500x70 cm
    "3041170CLM": (S5, 3, "Cumpleaños rosa, azul y blanco"),
    "3041174CLM": (S5, 3, "Kraft felicidades, rayas y topos"),
    "3041175CLM": (S5, 3, "Cuadros vichy beige, rosa y turquesa"),
    "3041176CLM": (S5, 3, "Estrellas gris, rosa y azul"),
    "3041224CLM": (S5, None, "Caga Tió en catalán, verde"),
    "3041339CLM": (S5, "m2", "Olentzero"),
    "3041529DCI": (S5, None, "Reyes Magos con camellos y palmeras"),
    "3041530DCI": (S5, 3, "Reyes Magos Melchor, Gaspar y Baltasar"),
    "3041531DCI": (S5, 3, "Papá Noel"),
    "3041532DCI": (S5, 3, "Elfos, caramelos y estrellas"),
    "3041533DCI": (S5, 3, "Papá Noel, regalos y estrellas"),
    "3041535DCI": (S5, 2, "Casas y árboles verde y beige"),
    "3041536DCI": (S5, 2, "Bastones de caramelo y estrellas rojo y verde"),
    "3041537DCI": (S5, 2, "Gorros de Papá Noel, caramelos y galletas"),
}


def design_name(sku, code):
    """Valor de `color` (diseño + lote) en el idioma del país."""
    _, pack, es = CHILDREN[sku]
    base = es if code == "ES" else DESIGN[es][("DE", "FR", "IT").index(code)]
    if pack is None:
        return base
    by_rolls, by_models = PACK[code]
    return f"{base}, {by_models(int(pack[1:])) if isinstance(pack, str) else by_rolls(pack)}"


EXCLUDED = {
    "29 en la lista de borrado / archivados": "304117, 304119, 304120, 304121, 3041105, 3041121, 3041132, 3041141, 3041146, 3041171-3041173, 3041177, 3041199, 3041204, 3041205, 3041207-3041212, 3041221-3041223, 3041267, 3041271 (CLM) y 304117CLMSELLERPRIME",
    "304107CLM": "ya borrado",
    "padres viejos": "PARENT-C500/C503/C505-PAPELDEREGAL, PARENT-OTROS-OTROS_PAPEL_DE_REGALO, P-NAVIDAD…, PARENT-DECORACIÓN…, PARENT-PELUCHE-PELUCHE_OSO: sus hijos de papel pasan a `papelregalo`",
    "otros productos": "bolsas, cajas, sobres, cintas, juegos de 25 piezas para envolver, manteles de papel en rollo, portarrollos",
}
