# Familia "Pulseras de chips de mineral ROCKING GIFTS" — tema COLOR_NAME (el mineral), BRACELET.
# Reutiliza el padre "pulseraschipmineral", cuyo tema en el catálogo es COLOR (Amazon obliga a mantenerlo);
# sus hijos se llamaban "Modelo 1…74" y pasan a llamarse por su mineral.
PRODUCT_TYPE = "BRACELET"
THEME = "COLOR_NAME"
MARKETS = {"ES": ("A1RKKUPIHCS9HS", "es_ES"), "DE": ("A1PA6795UKMFR9", "de_DE"), "FR": ("A13V1IB3VIYZZH", "fr_FR"), "IT": ("APJ6JRA9NG5V4", "it_IT")}

# sku: (ES, DE, FR, IT)
MINERALS = {
    "1154VC0": ("Amatista", "Amethyst", "Améthyste", "Ametista"),
    "1161VC0": ("Fluorita arcoíris", "Regenbogen-Fluorit", "Fluorite arc-en-ciel", "Fluorite arcobaleno"),
    "14815VCI": ("Fluorita verde, chip pequeño", "Grüner Fluorit, kleine Chips", "Fluorite verte, petits éclats", "Fluorite verde, chip piccoli"),
    "16084VCI": ("Fluorita multicolor", "Bunter Fluorit", "Fluorite multicolore", "Fluorite multicolore"),
    "1162RGVC": ("Ojo de tigre", "Tigerauge", "Œil de tigre", "Occhio di tigre"),
    "1968RGVC": ("Ojo de buey", "Ochsenauge", "Œil de taureau", "Occhio di bue"),
    "1163RGVC": ("Obsidiana", "Obsidian", "Obsidienne", "Ossidiana"),
    "1163VC": ("Obsidiana, modelo II", "Obsidian, Modell II", "Obsidienne, modèle II", "Ossidiana, modello II"),
    "14789VCI": ("Obsidiana caoba, chip pequeño", "Mahagoni-Obsidian, kleine Chips", "Obsidienne acajou, petits éclats", "Ossidiana mogano, chip piccoli"),
    "14803VCI": ("Obsidiana nevada, chip pequeño", "Schneeflocken-Obsidian, kleine Chips", "Obsidienne neige, petits éclats", "Ossidiana fiocco di neve, chip piccoli"),
    "1165VCI": ("Cornalina", "Karneol", "Cornaline", "Corniola"),
    "1167VCI": ("Calcedonia azul", "Blauer Chalcedon", "Calcédoine bleue", "Calcedonio blu"),
    "1168VC0": ("Cuarzo rosa", "Rosenquarz", "Quartz rose", "Quarzo rosa"),
    "1706VC": ("Cuarzo verde", "Grüner Quarz", "Quartz vert", "Quarzo verde"),
    "1972VCI": ("Cuarzo transparente", "Bergkristall", "Cristal de roche", "Cristallo di rocca"),
    "14943VCI": ("Cuarzo, chip pequeño", "Quarz, kleine Chips", "Quartz, petits éclats", "Quarzo, chip piccoli"),
    "1969RGVC": ("Cuarzo rutilado", "Rutilquarz", "Quartz rutile", "Quarzo rutilato"),
    "13438VCT": ("Cuarzo turmalinado", "Turmalinquarz", "Quartz tourmaliné", "Quarzo tormalinato"),
    "15938VCI": ("Cuarzo turmalinado, chip pequeño", "Turmalinquarz, kleine Chips", "Quartz tourmaliné, petits éclats", "Quarzo tormalinato, chip piccoli"),
    "13439VCT": ("Cuarzo ahumado", "Rauchquarz", "Quartz fumé", "Quarzo fumé"),
    "14929VCI": ("Cuarzo ahumado, chip pequeño", "Rauchquarz, kleine Chips", "Quartz fumé, petits éclats", "Quarzo fumé, chip piccoli"),
    "11596RGVC": ("Turmalina multicolor extra", "Bunter Turmalin Extra", "Tourmaline multicolore extra", "Tormalina multicolore extra"),
    "11596VC": ("Turmalina multicolor extra, chip pequeño", "Bunter Turmalin Extra, kleine Chips", "Tourmaline multicolore extra, petits éclats", "Tormalina multicolore extra, chip piccoli"),
    "4102RGVC": ("Turmalina bicolor", "Zweifarbiger Turmalin", "Tourmaline bicolore", "Tormalina bicolore"),
    "14790VCI": ("Sodalita, chip pequeño", "Sodalith, kleine Chips", "Sodalite, petits éclats", "Sodalite, chip piccoli"),
    "16088VCI": ("Sodalita", "Sodalith", "Sodalite", "Sodalite"),
    "14791VCI": ("Iolita, chip pequeño", "Iolith, kleine Chips", "Iolite, petits éclats", "Iolite, chip piccoli"),
    "14792VCI": ("Unakita, chip pequeño", "Unakit, kleine Chips", "Unakite, petits éclats", "Unakite, chip piccoli"),
    "14796VCI": ("Lepidolita, chip pequeño", "Lepidolith, kleine Chips", "Lépidolite, petits éclats", "Lepidolite, chip piccoli"),
    "14800VCI": ("Granate, chip pequeño", "Granat, kleine Chips", "Grenat, petits éclats", "Granato, chip piccoli"),
    "14801VCI": ("Angelita, chip pequeño", "Angelit, kleine Chips", "Angélite, petits éclats", "Angelite, chip piccoli"),
    "14802VCI": ("Jaspe dálmata, chip pequeño", "Dalmatiner-Jaspis, kleine Chips", "Jaspe dalmatien, petits éclats", "Diaspro dalmata, chip piccoli"),
    "14806VCI": ("Howlita teñida, chip pequeño", "Gefärbter Howlith, kleine Chips", "Howlite teintée, petits éclats", "Howlite tinta, chip piccoli"),
    "14811VCI": ("Howlita, chip pequeño", "Howlith, kleine Chips", "Howlite, petits éclats", "Howlite, chip piccoli"),
    "14807VCI": ("Labradorita, chip pequeño", "Labradorit, kleine Chips", "Labradorite, petits éclats", "Labradorite, chip piccoli"),
    "14813VCI": ("Aventurina verde, chip pequeño", "Grüner Aventurin, kleine Chips", "Aventurine verte, petits éclats", "Avventurina verde, chip piccoli"),
    "4762RGVC": ("Aguamarina", "Aquamarin", "Aigue-marine", "Acquamarina"),
    "14814VCI": ("Aguamarina, chip pequeño", "Aquamarin, kleine Chips", "Aigue-marine, petits éclats", "Acquamarina, chip piccoli"),
    "16081VCI": ("Aguamarina calidad A", "Aquamarin Qualität A", "Aigue-marine qualité A", "Acquamarina qualità A"),
    "14931VCI": ("Jaspe rojo, chip pequeño", "Roter Jaspis, kleine Chips", "Jaspe rouge, petits éclats", "Diaspro rosso, chip piccoli"),
    "16082VCI": ("Adularia", "Adular", "Adulaire", "Adularia"),
    "16089VCI": ("Ágata Botswana", "Botswana-Achat", "Agate du Botswana", "Agata Botswana"),
    "17263VCI": ("Ágata", "Achat", "Agate", "Agata"),
    "5716RGVC": ("Ágata musgosa", "Moosachat", "Agate mousse", "Agata muschiata"),
    "5716VCI": ("Ágata musgosa, chip pequeño", "Moosachat, kleine Chips", "Agate mousse, petits éclats", "Agata muschiata, chip piccoli"),
    "17903VCI": ("Jaspe leopardo", "Leopardenfell-Jaspis", "Jaspe léopard", "Diaspro leopardo"),
    "17904VCI": ("Jaspe mokaíta", "Mookait-Jaspis", "Jaspe mookaïte", "Diaspro mookaite"),
    "4152RGVC": ("Jaspe dalmanita", "Dalmatiner-Jaspis Dalmanit", "Jaspe dalmanite", "Diaspro dalmanite"),
    "17905VCI": ("Ópalo amarillo", "Gelber Opal", "Opale jaune", "Opale gialla"),
    "1967RGVC": ("Malaquita", "Malachit", "Malachite", "Malachite"),
    "2006RGVC": ("Ámbar", "Bernstein", "Ambre", "Ambra"),
    "2007RGVC": ("Ámbar combinado", "Bernstein gemischt", "Ambre mélangé", "Ambra mista"),
    "3005RGVC": ("Piedra luna", "Mondstein", "Pierre de lune", "Pietra di luna"),
    "3136RGVC": ("Larimar", "Larimar", "Larimar", "Larimar"),
    "3136VCI": ("Larimar, modelo II", "Larimar, Modell II", "Larimar, modèle II", "Larimar, modello II"),
    "3139RGVC": ("Zoisita con rubí", "Zoisit mit Rubin", "Zoïsite avec rubis", "Zoisite con rubino"),
    "3502RGVC": ("Jade", "Jade", "Jade", "Giada"),
    "5483RGVC": ("Jade nefrita", "Nephrit-Jade", "Jade néphrite", "Giada nefrite"),
    "3668RGVC": ("Peridoto", "Peridot", "Péridot", "Peridoto"),
    "4116RGVC": ("Apatito claro", "Heller Apatit", "Apatite claire", "Apatite chiara"),
    "4116VCI": ("Apatito claro, modelo II", "Heller Apatit, Modell II", "Apatite claire, modèle II", "Apatite chiara, modello II"),
    "4150RGVC": ("Kunzita", "Kunzit", "Kunzite", "Kunzite"),
    "4153RGVC": ("Aragonito", "Aragonit", "Aragonite", "Aragonite"),
    "5479RGVC": ("Rodocrosita", "Rhodochrosit", "Rhodochrosite", "Rodocrosite"),
    "5484RGVC": ("Cianita", "Kyanit", "Cyanite", "Cianite"),
    "9218VC": ("Goldstone", "Goldfluss", "Pierre de soleil (goldstone)", "Avventurina sintetica (goldstone)"),
    "9241VC": ("Sugilita calidad A", "Sugilith Qualität A", "Sugilite qualité A", "Sugilite qualità A"),
}

CHILDREN = list(MINERALS)

EXCLUDED = {
    "SKU FBA": "mismo ASIN que su SKU FBM (la variación es por ASIN)",
    "marca Mineral Import u otras": "no son ROCKING GIFTS en el catálogo",
    "archivadas/borradas": "en la lista de borrado o ya borradas",
    "Pack Caja Zodiaco": "son packs, no pulseras sueltas",
}
